import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discover Unique Places",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/earth.png", type: "image/png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FAFAFF] min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <header className="w-full py-6 px-4 bg-[#273469] text-[#FAFAFF] flex flex-col items-center border-b border-[#E4D9FF]">
            <div className="max-w-4xl w-full flex flex-col sm:flex-row items-center justify-between gap-2">
              <div className="flex items-center gap-3">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/globe.svg" alt="Globe" className="h-8 w-8" />
                <span className="text-2xl font-bold tracking-tight">Unique Places App</span>
              </div>
              <nav className="flex gap-6 text-base font-medium">
                <a href="#about" className="hover:underline">About</a>
                <a href="#how" className="hover:underline">How it Works</a>
                <a href="#contact" className="hover:underline">Contact</a>
              </nav>
            </div>
          </header>
          <main className="flex-1 flex flex-col items-center justify-center w-full">
            {children}
            <section id="about" className="max-w-2xl w-full mt-16 mb-8 px-4">
              <h2 className="text-xl font-semibold text-[#273469] mb-2">About</h2>
              <p className="text-[#30343F] text-base">
                Unique Places App helps you discover cool, offbeat, and hidden-gem things to do near any location. We filter out the generic tourist traps and focus on the truly unique experiences, so you can explore like a local and find something special wherever you go.
              </p>
            </section>
            <section id="how" className="max-w-2xl w-full mb-8 px-4">
              <h2 className="text-xl font-semibold text-[#273469] mb-2">How it Works</h2>
              <ul className="list-disc pl-6 text-[#30343F] text-base space-y-1">
                <li>Enter a city, address, or landmark in the search bar above.</li>
                <li>Adjust the search radius to find unique places nearby.</li>
                <li>Browse results and click for more info or directions.</li>
                <li>Try the <span className="font-semibold">Random</span> button for a surprise from around the world!</li>
              </ul>
            </section>
            <section id="contact" className="max-w-2xl w-full mb-16 px-4">
              <h2 className="text-xl font-semibold text-[#273469] mb-2">Contact</h2>
              <p className="text-[#30343F] text-base">
                Have feedback, want to suggest a unique place, or just want to say hi? Email us at <a href="mailto:hello@uniqueplaces.app" className="underline text-[#273469]">hello@uniqueplaces.app</a>.
              </p>
            </section>
          </main>
          <footer className="w-full py-6 px-4 bg-[#E4D9FF] text-[#273469] flex flex-col items-center border-t border-[#C1B2FA] mt-auto">
            <div className="max-w-4xl w-full flex flex-col sm:flex-row items-center justify-between gap-2">
              <span className="text-sm">&copy; {new Date().getFullYear()} Unique Places App. All rights reserved.</span>
              <span className="text-xs">Made with <span className="text-pink-500">♥</span> by your adventure-loving team.</span>
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
